Deploy test env

diff --git a/.github/workflows/deploy-mp.yml b/.github/workflows/deploy-mp.yml
--- a/.github/workflows/deploy-mp.yml
+++ b/.github/workflows/deploy-mp.yml
@@ -74,6 +74,7 @@ jobs:
           if [ "$environment" == 'test' ];     then account_name='delius-core-test'; hmpps_env_name='delius-test'; fi
           if [ "$environment" == 'stage' ];    then account_name='delius-core-stage'; hmpps_env_name='delius-stage'; fi
           if [ "$environment" == 'preprod' ];  then account_name='delius-core-preproduction'; hmpps_env_name='delius-pre-prod'; fi
+          if [ "$environment" == 'prod' ];     then account_name='delius-core-production'; hmpps_env_name='delius-prod'; fi
           echo "account_name=${account_name}"
           echo "hmpps_env_name=${hmpps_env_name}"
           echo "account_name=${account_name}" >> "$GITHUB_OUTPUT"
@@ -81,20 +82,29 @@ jobs:
         env:
           environment: ${{ inputs.environment }}
 
+      # Necessary for applying Terraform if no 'Version' input is supplied
       - name: Get currently running version of Weblogic/EIS
         id: get_current_version
+        if: ${{ inputs.version == '' }}
         run: |
           for SERVICE in weblogic weblogic-eis; do
+            TASK_DEFINITION=$(aws ecs describe-services \
+              --cluster "delius-core-${{ inputs.environment }}-cluster" \
+              --services "${{ inputs.environment }}-$SERVICE" \
+              --query 'services[0].taskDefinition' \
+              --output text)
+
+            if [[ -z "$TASK_DEFINITION" || "$TASK_DEFINITION" == "None" ]]; then
+              echo "Service '${{ inputs.environment }}-$SERVICE' is not deployed and no 'Version' input was provided."
+              echo "Please provide a 'Version' input to deploy the service for the first time."
+              exit 1
+            fi
+
             IMAGE=$(aws ecs describe-task-definition \
-              --task-definition "$(
-                aws ecs describe-services \
-                  --cluster "delius-core-${{ inputs.environment }}-cluster" \
-                  --services "${{ inputs.environment }}-$SERVICE" \
-                  --query 'services[0].taskDefinition' \
-                  --output text
-              )" \
+              --task-definition "$TASK_DEFINITION" \
               --query 'taskDefinition.containerDefinitions[0].image' \
               --output text)
+
             echo "Current ${SERVICE} version = ${IMAGE##*:}"
             echo "current_${SERVICE}_version=${IMAGE##*:}" >> "$GITHUB_OUTPUT"
           done
@@ -143,11 +153,11 @@ jobs:
             exit 1
           fi
 
-      - name: Stop Probation Integration updates
-        if: ${{ inputs.environment == 'test' || inputs.environment == 'stage' || inputs.environment == 'preprod' }}
-        run: gh workflow run readonly.yml --repo 'ministryofjustice/hmpps-probation-integration-services' --field 'action=enable' --field "environment=${{ inputs.environment }}"
-        env:
-          GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
+      # - name: Stop Probation Integration updates
+      #   if: ${{ inputs.environment == 'test' || inputs.environment == 'stage' || inputs.environment == 'preprod' }}
+      #   run: gh workflow run readonly.yml --repo 'ministryofjustice/hmpps-probation-integration-services' --field 'action=enable' --field "environment=${{ inputs.environment }}"
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
@@ -194,15 +204,15 @@ jobs:
           echo 'terraform apply -var-file="environments/${{ inputs.environment }}/terraform.tfvars" -var="weblogic_image_tag=${{ env.WEBLOGIC_IMAGE_TAG }}" -var="weblogic_eis_image_tag=${{ env.WEBLOGIC_EIS_IMAGE_TAG }}" $tfargs'
           terraform apply -var-file="environments/${{ inputs.environment }}/terraform.tfvars" -var="weblogic_image_tag=${{ env.WEBLOGIC_IMAGE_TAG }}" -var="weblogic_eis_image_tag=${{ env.WEBLOGIC_EIS_IMAGE_TAG }}" $tfargs
 
-      - name: Update configuration
-        id: config
-        shell: bash
-        run: ./.github/workflows/update-env-config.sh
-        env:
-          environment: ${{ steps.set_env_names.outputs.hmpps_env_name }}
-          rbac_version: ${{ inputs.rbac_version }}
-          version: ${{ steps.set_image_tag_vars.outputs.WEBLOGIC_IMAGE_TAG }}
-          token: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
+      # - name: Update configuration
+      #   id: config
+      #   shell: bash
+      #   run: ./.github/workflows/update-env-config.sh
+      #   env:
+      #     environment: ${{ steps.set_env_names.outputs.hmpps_env_name }}
+      #     rbac_version: ${{ inputs.rbac_version }}
+      #     version: ${{ steps.set_image_tag_vars.outputs.WEBLOGIC_IMAGE_TAG }}
+      #     token: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
 
       - name: Uplift RBAC in modernisation platform
         id: uplift_rbac
@@ -296,23 +306,23 @@ jobs:
           echo "ECS service not stable"
           exit 1
 
-      - name: Re-enable Probation Integration updates
-        if: ${{ inputs.environment == 'test' || inputs.environment == 'stage' || inputs.environment == 'preprod' }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
-        run: gh workflow run readonly.yml --repo 'ministryofjustice/hmpps-probation-integration-services' --field 'action=disable' --field "environment=${{ inputs.environment}}"
+      # - name: Re-enable Probation Integration updates
+      #   if: ${{ inputs.environment == 'test' || inputs.environment == 'stage' || inputs.environment == 'preprod' }}
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
+      #   run: gh workflow run readonly.yml --repo 'ministryofjustice/hmpps-probation-integration-services' --field 'action=disable' --field "environment=${{ inputs.environment}}"
 
-      - name: Revert version on failure
-        if: always() && steps.config.outputs.version_changed == 'true' && (steps.terraform_plan.outcome == 'failure' || steps.terraform_apply.outcome == 'failure' || steps.restart_weblogic.outcome == 'failure' || steps.uplift_rbac.outcome == 'failure')
-        working-directory: env_configs
-        shell: bash
-        env:
-          environment: ${{ inputs.environment }}
-          current_version: ${{ steps.config.outputs.current_version }}
-          version: ${{ steps.set_image_tag_vars.outputs.WEBLOGIC_IMAGE_TAG }}
-        run: |
-          sed -i "s/^ndelius_version:.*/ndelius_version: "'"'"$current_version"'"'"/" "$environment/ansible/group_vars/all.yml"
-          git commit -m "Rollback Delius v$version in $environment" \
-                     -m 'This was triggered by an automated deployment from https://github.com/ministryofjustice/delius-releases' \
-                     "$environment/ansible/group_vars/all.yml"
-          git push
+      # - name: Revert version on failure
+      #   if: always() && steps.config.outputs.version_changed == 'true' && (steps.terraform_plan.outcome == 'failure' || steps.terraform_apply.outcome == 'failure' || steps.restart_weblogic.outcome == 'failure' || steps.uplift_rbac.outcome == 'failure')
+      #   working-directory: env_configs
+      #   shell: bash
+      #   env:
+      #     environment: ${{ inputs.environment }}
+      #     current_version: ${{ steps.config.outputs.current_version }}
+      #     version: ${{ steps.set_image_tag_vars.outputs.WEBLOGIC_IMAGE_TAG }}
+      #   run: |
+      #     sed -i "s/^ndelius_version:.*/ndelius_version: "'"'"$current_version"'"'"/" "$environment/ansible/group_vars/all.yml"
+      #     git commit -m "Rollback Delius v$version in $environment" \
+      #                -m 'This was triggered by an automated deployment from https://github.com/ministryofjustice/delius-releases' \
+      #                "$environment/ansible/group_vars/all.yml"
+      #     git push
