add github token + env var

diff --git a/.github/workflows/deploy-mp.yml b/.github/workflows/deploy-mp.yml
--- a/.github/workflows/deploy-mp.yml
+++ b/.github/workflows/deploy-mp.yml
@@ -99,15 +99,15 @@ jobs:
           version: ${{ inputs.version }}
           token: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
 
-      - name: Uplift RBAC in modernisation platform
-        id: uplift_rbac
-        if: steps.modernisation_platform_environment.outputs.name != ''
-        shell: bash
-        run: gh workflow run ldap-rbac-uplift.yml --repo 'ministryofjustice/hmpps-delius-operational-automation' --field "environment=$modernisation_platform_environment" --field "rbac_tag=$rbac_tag"
-        env:
-          modernisation_platform_environment: ${{ steps.modernisation_platform_environment.outputs.name }}
-          rbac_tag: ${{ inputs.rbac_version }}
-          GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
+      # - name: Uplift RBAC in modernisation platform
+      #   id: uplift_rbac
+      #   if: steps.modernisation_platform_environment.outputs.name != ''
+      #   shell: bash
+      #   run: gh workflow run ldap-rbac-uplift.yml --repo 'ministryofjustice/hmpps-delius-operational-automation' --field "environment=$modernisation_platform_environment" --field "rbac_tag=$rbac_tag"
+      #   env:
+      #     modernisation_platform_environment: ${{ steps.modernisation_platform_environment.outputs.name }}
+      #     rbac_tag: ${{ inputs.rbac_version }}
+      #     GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
 
       - name: Uplift PDM in modernisation platform
         id: uplift_pdm
@@ -123,61 +123,61 @@ jobs:
           version: ${{ inputs.version }}
           GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
 
-      - name: Start automation
-        id: start_automation
-        if: steps.config.outputs.version_changed == 'true' || github.event_name == 'workflow_dispatch' # only deploy if version changed, or if started manually
-        shell: bash
-        run: |
-          # start the execution
-          execution=$(aws ssm start-automation-execution --document-name "${short_environment_name}-Delius-DeployApplication" --region eu-west-2 --parameters DeployDatabase=no)
-          execution_id=$(echo "$execution" | jq -r '.AutomationExecutionId')
-          echo "execution_id=$execution_id" | tee -a $GITHUB_OUTPUT
+      # - name: Start automation
+      #   id: start_automation
+      #   if: steps.config.outputs.version_changed == 'true' || github.event_name == 'workflow_dispatch' # only deploy if version changed, or if started manually
+      #   shell: bash
+      #   run: |
+      #     # start the execution
+      #     execution=$(aws ssm start-automation-execution --document-name "${short_environment_name}-Delius-DeployApplication" --region eu-west-2 --parameters DeployDatabase=no)
+      #     execution_id=$(echo "$execution" | jq -r '.AutomationExecutionId')
+      #     echo "execution_id=$execution_id" | tee -a $GITHUB_OUTPUT
 
-          # output useful links
-          echo "Execution started. Check the status in AWS Systems Manager: https://eu-west-2.console.aws.amazon.com/systems-manager/automation/execution/${execution_id}?region=eu-west-2"
-          while [ -z "$codebuild_link" ]; do codebuild_link=$(aws ssm get-automation-execution --automation-execution-id "$execution_id" --query "AutomationExecution.StepExecutions[?StepName == 'OutputBuildDetails'].Outputs.CodeBuildLink[]" --output text); sleep 1; done
-          echo "View the logs in AWS CodeBuild: $codebuild_link"
-        env:
-          short_environment_name: ${{ steps.config.outputs.short_environment_name }}
+      #     # output useful links
+      #     echo "Execution started. Check the status in AWS Systems Manager: https://eu-west-2.console.aws.amazon.com/systems-manager/automation/execution/${execution_id}?region=eu-west-2"
+      #     while [ -z "$codebuild_link" ]; do codebuild_link=$(aws ssm get-automation-execution --automation-execution-id "$execution_id" --query "AutomationExecution.StepExecutions[?StepName == 'OutputBuildDetails'].Outputs.CodeBuildLink[]" --output text); sleep 1; done
+      #     echo "View the logs in AWS CodeBuild: $codebuild_link"
+      #   env:
+      #     short_environment_name: ${{ steps.config.outputs.short_environment_name }}
 
-      - name: Wait for automation to complete
-        id: wait_for_automation
-        if: steps.config.outputs.version_changed == 'true' || github.event_name == 'workflow_dispatch' # only deploy if version changed, or if started manually
-        shell: bash
-        run: |
-          # output useful links
-          echo "Execution started. Check the status in AWS Systems Manager: https://eu-west-2.console.aws.amazon.com/systems-manager/automation/execution/${execution_id}?region=eu-west-2"
-          while [ -z "$codebuild_link" ]; do codebuild_link=$(aws ssm get-automation-execution --automation-execution-id "$execution_id" --query "AutomationExecution.StepExecutions[?StepName == 'OutputBuildDetails'].Outputs.CodeBuildLink[]" --output text); sleep 1; done
-          echo "View the logs in AWS CodeBuild: $codebuild_link"
+      # - name: Wait for automation to complete
+      #   id: wait_for_automation
+      #   if: steps.config.outputs.version_changed == 'true' || github.event_name == 'workflow_dispatch' # only deploy if version changed, or if started manually
+      #   shell: bash
+      #   run: |
+      #     # output useful links
+      #     echo "Execution started. Check the status in AWS Systems Manager: https://eu-west-2.console.aws.amazon.com/systems-manager/automation/execution/${execution_id}?region=eu-west-2"
+      #     while [ -z "$codebuild_link" ]; do codebuild_link=$(aws ssm get-automation-execution --automation-execution-id "$execution_id" --query "AutomationExecution.StepExecutions[?StepName == 'OutputBuildDetails'].Outputs.CodeBuildLink[]" --output text); sleep 1; done
+      #     echo "View the logs in AWS CodeBuild: $codebuild_link"
 
-          # wait for the execution to complete
-          status="Started"
-          start_time=$SECONDS
-          while [ "$status" != "Success" -a "$status" != "Failed" -a "$status" != "TimedOut" -a "$status" != "Cancelled" ]; do
-            status=$(aws ssm get-automation-execution --automation-execution-id "$execution_id" --query 'AutomationExecution.AutomationExecutionStatus' --output text)
-            sleep 1
-          done
+      #     # wait for the execution to complete
+      #     status="Started"
+      #     start_time=$SECONDS
+      #     while [ "$status" != "Success" -a "$status" != "Failed" -a "$status" != "TimedOut" -a "$status" != "Cancelled" ]; do
+      #       status=$(aws ssm get-automation-execution --automation-execution-id "$execution_id" --query 'AutomationExecution.AutomationExecutionStatus' --output text)
+      #       sleep 1
+      #     done
 
-          # output the summary
-          echo Execution completed. Status: $status
-          duration=$(( SECONDS - start_time ))
-          status_icon=$(test "$status" == "Success" && echo ':white_check_mark:' || echo ':x:')
-          echo '### Deployment Complete' >> $GITHUB_STEP_SUMMARY
-          echo "| Environment | $environment |" >> $GITHUB_STEP_SUMMARY
-          echo '| :--- | :--- |' >> $GITHUB_STEP_SUMMARY
-          echo "| Status | $status_icon $status |" >> $GITHUB_STEP_SUMMARY
-          echo "| Duration | :stopwatch: $((duration/60))m $((duration%60))s |" >> $GITHUB_STEP_SUMMARY
-          echo "| Logs | :memo: [View the logs in AWS CodeBuild]($codebuild_link) |" >> $GITHUB_STEP_SUMMARY
+      #     # output the summary
+      #     echo Execution completed. Status: $status
+      #     duration=$(( SECONDS - start_time ))
+      #     status_icon=$(test "$status" == "Success" && echo ':white_check_mark:' || echo ':x:')
+      #     echo '### Deployment Complete' >> $GITHUB_STEP_SUMMARY
+      #     echo "| Environment | $environment |" >> $GITHUB_STEP_SUMMARY
+      #     echo '| :--- | :--- |' >> $GITHUB_STEP_SUMMARY
+      #     echo "| Status | $status_icon $status |" >> $GITHUB_STEP_SUMMARY
+      #     echo "| Duration | :stopwatch: $((duration/60))m $((duration%60))s |" >> $GITHUB_STEP_SUMMARY
+      #     echo "| Logs | :memo: [View the logs in AWS CodeBuild]($codebuild_link) |" >> $GITHUB_STEP_SUMMARY
 
-          # check the status
-          test "$status" == "Success"
-        env:
-          environment: ${{ inputs.environment }}
-          execution_id: ${{ steps.start_automation.outputs.execution_id }}
+      #     # check the status
+      #     test "$status" == "Success"
+      #   env:
+      #     environment: ${{ inputs.environment }}
+      #     execution_id: ${{ steps.start_automation.outputs.execution_id }}
 
       - name: Wait for DB Uplift automation to complete
         run: |
-          run_id="${{ steps.uplift_pdm.outputs.run_id }}"
+          run_id="$uplift_run_id"
 
           status="in_progress"
           while [[ "$status" == "in_progress" || "$status" == "queued" ]]; do
@@ -194,6 +194,9 @@ jobs:
           else
             echo "PDM Uplift completed successfully."
           fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
+          uplift_run_id: ${{ steps.uplift_pdm.outputs.run_id }}
 
       - name: Re-enable Probation Integration updates
         if: steps.integration_environment.outputs.name != ''
