Test image version checker

diff --git a/.github/workflows/deploy-mp.yml b/.github/workflows/deploy-mp.yml
--- a/.github/workflows/deploy-mp.yml
+++ b/.github/workflows/deploy-mp.yml
@@ -123,14 +123,16 @@ jobs:
           WEBLOGIC_EIS_IMAGE_TAG: ${{ steps.set_image_tag_vars.outputs.WEBLOGIC_EIS_IMAGE_TAG }}
         run: |
           echo "Checking if WebLogic image exists in ECR..."
-          if ! aws ecr describe-images --registry-id "374269020027" --repository-name "delius-core-weblogic" --image-ids imageTag="$WEBLOGIC_IMAGE_TAG" >/dev/null 2>&1; then
-            echo "Error: Image tag $WEBLOGIC_IMAGE_TAG for WebLogic does not exist in ECR repository delius-core-weblogic."
+          if ! ERROR=$(aws ecr describe-images --registry-id "374269020027" --repository-name "delius-core-weblogic" --image-ids imageTag="$WEBLOGIC_IMAGE_TAG" >/dev/null 2>&1); then
+            echo "$ERROR"
+            # echo "Error: Image tag $WEBLOGIC_IMAGE_TAG for WebLogic does not exist in ECR repository delius-core-weblogic."
             exit 1
           fi
 
           echo "Checking if WebLogic EIS image exists in ECR..."
-          if ! aws ecr describe-images --registry-id "374269020027" --repository-name "delius-core-weblogic" --image-ids imageTag="$WEBLOGIC_EIS_IMAGE_TAG" >/dev/null 2>&1; then
-            echo "Error: Image tag $WEBLOGIC_EIS_IMAGE_TAG for WebLogic EIS does not exist in ECR repository delius-core-weblogic."
+          if ! ERROR=$(aws ecr describe-images --registry-id "374269020027" --repository-name "delius-core-weblogic" --image-ids imageTag="$WEBLOGIC_EIS_IMAGE_TAG" >/dev/null 2>&1); then
+            echo "$ERROR"
+            # echo "Error: Image tag $WEBLOGIC_EIS_IMAGE_TAG for WebLogic EIS does not exist in ECR repository delius-core-weblogic."
             exit 1
           fi
 
