Add Github env var

diff --git a/.github/workflows/deploy-mp-old.yml b/.github/workflows/deploy-mp-old.yml
--- a/.github/workflows/deploy-mp-old.yml
+++ b/.github/workflows/deploy-mp-old.yml
@@ -1,4 +1,4 @@
-name: Deploy
+name: Deploy Mod Platform
 
 on:
   # Allow a deployment to be started from the pipeline
@@ -109,13 +109,27 @@ jobs:
           rbac_tag: ${{ inputs.rbac_version }}
           GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
 
+      - name: Uplift PDM in modernisation platform
+        id: uplift_pdm
+        if: steps.modernisation_platform_environment.outputs.name != ''
+        shell: bash
+        run: |
+          gh workflow run delius-db-pdm-uplift.yml --repo 'ministryofjustice/hmpps-delius-operational-automation' --field "TargetEnvironment=delius-core-$modernisation_platform_environment" --field "Version=$version" --field "CreateRestorePoint=No"
+          sleep 5
+          run_id=$(gh run list --repo ministryofjustice/hmpps-delius-operational-automation --workflow delius-db-pdm-uplift.yml --limit 1 --json databaseId -q '.[0].databaseId')
+          echo "run_id=$run_id" >> "$GITHUB_OUTPUT"
+        env:
+          modernisation_platform_environment: ${{ steps.modernisation_platform_environment.outputs.name }}
+          version: ${{ inputs.version }}
+          GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
+
       - name: Start automation
         id: start_automation
         if: steps.config.outputs.version_changed == 'true' || github.event_name == 'workflow_dispatch' # only deploy if version changed, or if started manually
         shell: bash
         run: |
           # start the execution
-          execution=$(aws ssm start-automation-execution --document-name "${short_environment_name}-Delius-DeployApplication" --region eu-west-2)
+          execution=$(aws ssm start-automation-execution --document-name "${short_environment_name}-Delius-DeployApplication" --region eu-west-2 --parameters DeployDatabase=no)
           execution_id=$(echo "$execution" | jq -r '.AutomationExecutionId')
           echo "execution_id=$execution_id" | tee -a $GITHUB_OUTPUT
 
@@ -161,6 +175,69 @@ jobs:
           environment: ${{ inputs.environment }}
           execution_id: ${{ steps.start_automation.outputs.execution_id }}
 
+      - name: Wait for DB Uplift automation to complete
+        run: |
+          run_id="$uplift_run_id"
+
+          status="in_progress"
+          while [[ "$status" == "in_progress" || "$status" == "queued" || "$status" == "waiting" ]]; do
+            echo "Waiting for run $run_id to complete..."
+            sleep 10
+            status=$(gh run view "$run_id" --repo ministryofjustice/hmpps-delius-operational-automation --json status -q '.status')
+          done
+
+          conclusion=$(gh run view "$run_id" --repo ministryofjustice/hmpps-delius-operational-automation --json conclusion -q '.conclusion')
+          if [[ "$conclusion" != "success" ]]; then
+            echo "PDM Uplift failed with status: $conclusion"
+            echo "To check the logs use the following URL: https://github.com/ministryofjustice/hmpps-delius-operational-automation/actions/runs/$run_id"
+            exit 1
+          else
+            echo "PDM Uplift completed successfully."
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
+          uplift_run_id: ${{ steps.uplift_pdm.outputs.run_id }}
+
+      - name: Restart weblogic after database uplift to re-establish connection
+        run: |
+          cluster_name="del-delius-ecscluster-private-ecs"
+          service_name="del-$environment-weblogic-app-service"
+
+          if [ "$environment" = "dev" ]; then
+            cluster_name="dmd-delius-ecscluster-private-ecs"
+            service_name="dmd-mis-dev-weblogic-app-service"
+          fi
+
+          echo "Forcing new weblogic deployment"
+
+          aws ecs update-service \
+            --cluster "$cluster_name" \
+            --service "$service_name" \
+            --force-new-deployment
+
+          MAX_RETRIES=2
+          COUNT=1
+
+          while [ $COUNT -le $MAX_RETRIES ]; do
+            echo "Waiting for ECS service to stabilize: Attempt ($COUNT/$MAX_RETRIES)"
+
+            if aws ecs wait services-stable \
+              --cluster "$cluster_name" \
+              --services "$service_name"; then
+              echo "ECS service has been successfully restarted"
+              exit 0
+            fi
+
+            echo "Attempt ($COUNT/$MAX_RETRIES) failed"
+            COUNT=$((COUNT + 1))
+          done
+
+          echo "ECS service not stable"
+          exit 1
+
+        env:
+          environment: ${{ steps.modernisation_platform_environment.outputs.name }}
+
       - name: Re-enable Probation Integration updates
         if: steps.integration_environment.outputs.name != ''
         run: gh workflow run readonly.yml --repo 'ministryofjustice/hmpps-probation-integration-services' --field 'action=disable' --field "environment=$environment"
@@ -182,4 +259,5 @@ jobs:
           environment: ${{ inputs.environment }}
           execution_id: ${{ steps.start_automation.outputs.execution_id }}
           current_version: ${{ steps.config.outputs.current_version }}
+
           version: ${{ inputs.version }}
