Reintroduce PDM/DM uplift steps

diff --git a/.github/workflows/deploy-mp.yml b/.github/workflows/deploy-mp.yml
--- a/.github/workflows/deploy-mp.yml
+++ b/.github/workflows/deploy-mp.yml
@@ -4,6 +4,11 @@ on:
   # Allow a deployment to be started from the pipeline
   workflow_call:
     inputs:
+      terraform_apply_only:
+        description: Only runs steps that apply terraform changes, skipping the RBAC and PDM uplift steps
+        type: boolean
+        required: false
+        default: false
       weblogic_version:
         description: Delius version
         type: string
@@ -23,6 +28,11 @@ on:
   # Allow a deployment to be started from the UI
   workflow_dispatch:
     inputs:
+      terraform_apply_only:
+        description: Only runs steps that apply terraform changes, skipping the RBAC and PDM uplift steps
+        type: boolean
+        required: false
+        default: false
       weblogic_version:
         description: Delius version
         type: string
@@ -136,11 +146,11 @@ jobs:
             exit 1
           fi
 
-      # - name: Stop Probation Integration updates
-      #   if: ${{ inputs.environment == 'test' || inputs.environment == 'stage' || inputs.environment == 'preprod' }}
-      #   run: gh workflow run readonly.yml --repo 'ministryofjustice/hmpps-probation-integration-services' --field 'action=enable' --field "environment=${{ inputs.environment }}"
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
+      - name: Stop Probation Integration updates
+        if: ${{ inputs.environment == 'test' || inputs.environment == 'stage' || inputs.environment == 'preprod' }}
+        run: gh workflow run readonly.yml --repo 'ministryofjustice/hmpps-probation-integration-services' --field 'action=enable' --field "environment=${{ inputs.environment }}"
+        env:
+          GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
@@ -158,7 +168,7 @@ jobs:
           terraform workspace select -or-create ${{ env.account_name }}
 
       - name: Terraform Plan
-        id: plan
+        id: terraform_plan
         env:
           WEBLOGIC_IMAGE_TAG: ${{ steps.set_image_tag_vars.outputs.WEBLOGIC_IMAGE_TAG }}
           WEBLOGIC_EIS_IMAGE_TAG: ${{ steps.set_image_tag_vars.outputs.WEBLOGIC_EIS_IMAGE_TAG }}
@@ -174,7 +184,8 @@ jobs:
           (( exitcode == 1 )) && exit 1 || exit 0
 
       - name: Terraform Apply
-        if: steps.plan.outputs.exitcode == '2'
+        id: terraform_apply
+        if: steps.terraform_plan.outputs.exitcode == '2'
         env:
           WEBLOGIC_IMAGE_TAG: ${{ steps.set_image_tag_vars.outputs.WEBLOGIC_IMAGE_TAG }}
           WEBLOGIC_EIS_IMAGE_TAG: ${{ steps.set_image_tag_vars.outputs.WEBLOGIC_EIS_IMAGE_TAG }}
@@ -186,64 +197,67 @@ jobs:
           echo 'terraform apply -var-file="environments/${{ inputs.environment }}/terraform.tfvars" -var="weblogic_image_tag=${{ env.WEBLOGIC_IMAGE_TAG }}" -var="weblogic_eis_image_tag=${{ env.WEBLOGIC_EIS_IMAGE_TAG }}" $tfargs'
           terraform apply -var-file="environments/${{ inputs.environment }}/terraform.tfvars" -var="weblogic_image_tag=${{ env.WEBLOGIC_IMAGE_TAG }}" -var="weblogic_eis_image_tag=${{ env.WEBLOGIC_EIS_IMAGE_TAG }}" $tfargs
 
-      # - name: Update configuration
-      #   id: config
-      #   shell: bash
-      #   run: ./.github/workflows/update-env-config.sh
-      #   env:
-      #     environment: ${{ inputs.environment }}
-      #     rbac_version: ${{ inputs.rbac_version }}
-      #     version: ${{ env.WEBLOGIC_IMAGE_TAG }}
-      #     token: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
+      - name: Update configuration
+        id: config
+        shell: bash
+        run: ./.github/workflows/update-env-config.sh
+        env:
+          environment: ${{ inputs.environment }}
+          rbac_version: ${{ inputs.rbac_version }}
+          version: ${{ steps.set_image_tag_vars.outputs.WEBLOGIC_IMAGE_TAG }}
+          token: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
 
-      # - name: Uplift RBAC in modernisation platform
-      #   id: uplift_rbac
-      #   if: steps.modernisation_platform_environment.outputs.name != ''
-      #   shell: bash
-      #   run: gh workflow run ldap-rbac-uplift.yml --repo 'ministryofjustice/hmpps-delius-operational-automation' --field "environment=$modernisation_platform_environment" --field "rbac_tag=$rbac_tag"
-      #   env:
-      #     modernisation_platform_environment: ${{ steps.modernisation_platform_environment.outputs.name }}
-      #     rbac_tag: ${{ inputs.rbac_version }}
-      #     GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
+      - name: Uplift RBAC in modernisation platform
+        id: uplift_rbac
+        if: ${{ steps.modernisation_platform_environment.outputs.name != '' || inputs.terraform_apply_only == false }}
+        shell: bash
+        run: gh workflow run ldap-rbac-uplift.yml --repo 'ministryofjustice/hmpps-delius-operational-automation' --field "environment=$modernisation_platform_environment" --field "rbac_tag=$rbac_tag"
+        env:
+          modernisation_platform_environment: ${{ steps.modernisation_platform_environment.outputs.name }}
+          rbac_tag: ${{ inputs.rbac_version }}
+          GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
 
-      # - name: Uplift PDM in modernisation platform
-      #   id: uplift_pdm
-      #   if: steps.modernisation_platform_environment.outputs.name != ''
-      #   shell: bash
-      #   run: |
-      #     gh workflow run delius-db-pdm-uplift.yml --repo 'ministryofjustice/hmpps-delius-operational-automation' --field "TargetEnvironment=delius-core-$modernisation_platform_environment" --field "Version=$version" --field "CreateRestorePoint=No"
-      #     sleep 5
-      #     run_id=$(gh run list --repo ministryofjustice/hmpps-delius-operational-automation --workflow delius-db-pdm-uplift.yml --limit 1 --json databaseId -q '.[0].databaseId')
-      #     echo "run_id=$run_id" >> "$GITHUB_OUTPUT"
-      #   env:
-      #     modernisation_platform_environment: ${{ steps.modernisation_platform_environment.outputs.name }}
-      #     version: ${{ inputs.version }}
-      #     GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
+      - name: Uplift PDM in modernisation platform
+        id: uplift_pdm
+        if: ${{ steps.modernisation_platform_environment.outputs.name != '' || inputs.terraform_apply_only == false }}
+        shell: bash
+        run: |
+          gh workflow run delius-db-pdm-uplift.yml --repo 'ministryofjustice/hmpps-delius-operational-automation' --field "TargetEnvironment=delius-core-$modernisation_platform_environment" --field "Version=$version" --field "CreateRestorePoint=No"
+          sleep 5
+          run_id=$(gh run list --repo ministryofjustice/hmpps-delius-operational-automation --workflow delius-db-pdm-uplift.yml --limit 1 --json databaseId -q '.[0].databaseId')
+          echo "run_id=$run_id" >> "$GITHUB_OUTPUT"
+        env:
+          modernisation_platform_environment: ${{ steps.modernisation_platform_environment.outputs.name }}
+          version: ${{ steps.set_image_tag_vars.outputs.WEBLOGIC_IMAGE_TAG }}
+          GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
 
-      # - name: Wait for DB Uplift automation to complete
-      #   run: |
-      #     run_id="$uplift_run_id"
+      - name: Wait for DB Uplift automation to complete
+        if: ${{ steps.modernisation_platform_environment.outputs.name != '' || inputs.terraform_apply_only == false }}
+        run: |
+          run_id="$uplift_run_id"
 
-      #     status="in_progress"
-      #     while [[ "$status" == "in_progress" || "$status" == "queued" || "$status" == "waiting" ]]; do
-      #       echo "Waiting for run $run_id to complete..."
-      #       sleep 10
-      #       status=$(gh run view "$run_id" --repo ministryofjustice/hmpps-delius-operational-automation --json status -q '.status')
-      #     done
+          status="in_progress"
+          while [[ "$status" == "in_progress" || "$status" == "queued" || "$status" == "waiting" ]]; do
+            echo "Waiting for run $run_id to complete..."
+            sleep 10
+            status=$(gh run view "$run_id" --repo ministryofjustice/hmpps-delius-operational-automation --json status -q '.status')
+          done
 
-      #     conclusion=$(gh run view "$run_id" --repo ministryofjustice/hmpps-delius-operational-automation --json conclusion -q '.conclusion')
-      #     if [[ "$conclusion" != "success" ]]; then
-      #       echo "PDM Uplift failed with status: $conclusion"
-      #       echo "To check the logs use the following URL: https://github.com/ministryofjustice/hmpps-delius-operational-automation/actions/runs/$run_id"
-      #       exit 1
-      #     else
-      #       echo "PDM Uplift completed successfully."
-      #     fi
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
-      #     uplift_run_id: ${{ steps.uplift_pdm.outputs.run_id }}
+          conclusion=$(gh run view "$run_id" --repo ministryofjustice/hmpps-delius-operational-automation --json conclusion -q '.conclusion')
+          if [[ "$conclusion" != "success" ]]; then
+            echo "PDM Uplift failed with status: $conclusion"
+            echo "To check the logs use the following URL: https://github.com/ministryofjustice/hmpps-delius-operational-automation/actions/runs/$run_id"
+            exit 1
+          else
+            echo "PDM Uplift completed successfully."
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
+          uplift_run_id: ${{ steps.uplift_pdm.outputs.run_id }}
 
       - name: Restart weblogic after database uplift to re-establish connection
+        id: restart_weblogic
+        if: ${{ steps.modernisation_platform_environment.outputs.name != '' || inputs.terraform_apply_only == false }}
         env:
           environment: ${{ steps.modernisation_platform_environment.outputs.account_name }}
         run: | 
@@ -287,25 +301,23 @@ jobs:
           echo "ECS service not stable"
           exit 1
 
-      # - name: Re-enable Probation Integration updates
-      #   if: steps.integration_environment.outputs.name != ''
-      #   run: gh workflow run readonly.yml --repo 'ministryofjustice/hmpps-probation-integration-services' --field 'action=disable' --field "environment=$environment"
-      #   env:
-      #     environment: ${{ steps.integration_environment.outputs.name }}
-      #     GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
+      - name: Re-enable Probation Integration updates
+        if: ${{ inputs.environment == 'test' || inputs.environment == 'stage' || inputs.environment == 'preprod' }}
+        run: gh workflow run readonly.yml --repo 'ministryofjustice/hmpps-probation-integration-services' --field 'action=disable' --field "environment=${{ inputs.environment}}"
+        env:
+          GITHUB_TOKEN: ${{ secrets.UNILINK_BOT_GITHUB_TOKEN }}
 
-      # - name: Revert version on failure
-      #   if: always() && steps.config.outputs.version_changed == 'true' && (steps.start_automation.outcome == 'failure' || steps.wait_for_automation.outcome == 'failure' || steps.uplift_rbac.outcome == 'failure')
-      #   working-directory: env_configs
-      #   shell: bash
-      #   run: |
-      #     sed -i "s/^ndelius_version:.*/ndelius_version: "'"'"$current_version"'"'"/" "$environment/ansible/group_vars/all.yml"
-      #     git commit -m "Rollback Delius v$version in $environment" \
-      #                -m 'This was triggered by an automated deployment from https://github.com/ministryofjustice/delius-releases' \
-      #                "$environment/ansible/group_vars/all.yml"
-      #     git push
-      #   env:
-      #     environment: ${{ inputs.environment }}
-      #     execution_id: ${{ steps.start_automation.outputs.execution_id }}
-      #     current_version: ${{ steps.config.outputs.current_version }}
-      #     version: ${{ inputs.version }}
+      - name: Revert version on failure
+        if: always() && steps.config.outputs.version_changed == 'true' && (steps.terraform_plan.outcome == 'failure' || steps.terraform_apply.outcome == 'failure' || steps.restart_weblogic.outcome == 'failure' || steps.uplift_rbac.outcome == 'failure')
+        working-directory: env_configs
+        shell: bash
+        run: |
+          sed -i "s/^ndelius_version:.*/ndelius_version: "'"'"$current_version"'"'"/" "$environment/ansible/group_vars/all.yml"
+          git commit -m "Rollback Delius v$version in $environment" \
+                     -m 'This was triggered by an automated deployment from https://github.com/ministryofjustice/delius-releases' \
+                     "$environment/ansible/group_vars/all.yml"
+          git push
+        env:
+          environment: ${{ inputs.environment }}
+          current_version: ${{ steps.config.outputs.current_version }}
+          version: ${{ steps.set_image_tag_vars.outputs.WEBLOGIC_IMAGE_TAG }}
